import { Injectable, inject, signal } from '@angular/core';
import { Logger } from './logger.service';

export type LanguageCode = 'fr' | 'en' | 'es' | 'pt' | 'ar' | 'sw' | 'fang';

export interface TranslationRequest {
  text: string;
  source?: LanguageCode;
  target: LanguageCode;
}

export interface TranslationResult {
  text: string;
  source: LanguageCode;
  target: LanguageCode;
  /** True when the translation was generated by an LLM. False when it
   *  came from a curated human dictionary. */
  aiGenerated: boolean;
}

/**
 * Provider contract. Wire any concrete backend (DeepL, in-house Edge
 * Function, Gemini, etc.) by `useFactory`-ing this token. The gateway
 * stays untouched and the rest of the app keeps the same interface.
 */
export abstract class TranslationProvider {
  abstract translate(req: TranslationRequest): Promise<TranslationResult>;
}

const STORAGE_KEY = 'cake_translation_consent';

/**
 * Translation **boundary**, not an implementation. Two reasons it lives
 * as a service:
 *
 *  1. **Consent gate.** Users must opt in to AI-assisted translation.
 *     Until they do, requests bail out to the original text. This is
 *     consistent with the brand promise of an "IA backstage but never
 *     surprised by it" product.
 *
 *  2. **In-memory cache.** Article titles repeat across sessions and we
 *     never need to translate them more than once per language pair.
 *
 * The actual provider is plugged at bootstrap time via Angular DI. Until
 * that wiring exists, the service operates in pass-through mode, which
 * makes the rest of the app safe to rely on it now.
 */
@Injectable({ providedIn: 'root' })
export class TranslationGatewayService {
  private logger = inject(Logger);
  private provider = inject(TranslationProvider, { optional: true });

  readonly aiConsent = signal<boolean>(this.loadConsent());

  setAiConsent(value: boolean) {
    this.aiConsent.set(value);
    try { localStorage.setItem(STORAGE_KEY, value ? '1' : '0'); } catch { /* ignore */ }
  }

  /** Translate a string, falling back to the original on any failure. */
  async translate(req: TranslationRequest): Promise<TranslationResult> {
    const source = req.source ?? this.guessLanguage(req.text);

    if (source === req.target) {
      return { text: req.text, source, target: req.target, aiGenerated: false };
    }

    if (!this.provider || !this.aiConsent()) {
      // Honest fallback — return source text untouched, mark as not AI.
      return { text: req.text, source, target: req.target, aiGenerated: false };
    }

    const cached = this.cache.get(this.cacheKey(req.text, source, req.target));
    if (cached) return cached;

    try {
      const result = await this.provider.translate({ ...req, source });
      this.cache.set(this.cacheKey(req.text, source, req.target), result);
      return result;
    } catch (e) {
      this.logger.warn('translation provider failed', e);
      return { text: req.text, source, target: req.target, aiGenerated: false };
    }
  }

  // ────────────────────────────────────────────────────────────────

  private cache = new Map<string, TranslationResult>();

  private cacheKey(text: string, source: LanguageCode, target: LanguageCode): string {
    // Hash-light: text length + first 32 chars + langs is enough to
    // disambiguate without a real hash dependency.
    const head = text.slice(0, 32).replace(/\s+/g, ' ');
    return `${source}>${target}|${text.length}|${head}`;
  }

  private guessLanguage(_text: string): LanguageCode {
    // Conservative default — the app is French-first. A production
    // deployment would call a `franc`-style detector.
    return 'fr';
  }

  private loadConsent(): boolean {
    try { return localStorage.getItem(STORAGE_KEY) === '1'; } catch { return false; }
  }
}
